[versions]
adventrue = "5.1.1"
paper = '26.2.build.47-alpha'
velocity = "3.5.0-SNAPSHOT"

[libraries]
paper-api = { module = 'io.papermc.paper:paper-api', version.ref = 'paper' }
velocity-api = { module = "com.velocitypowered:velocity-api", version.ref = 'velocity' }

adventure-api = { group = "net.kyori", name = "adventure-api", version.ref = "adventrue" }
adventure-text-minimessage = { group = "net.kyori", name = "adventure-text-minimessage", version.ref = "adventrue" }
adventure-text-serializer-gson = { group = "net.kyori", name = "adventure-text-serializer-gson", version.ref = "adventrue" }
adventure-text-serializer-legacy = { group = "net.kyori", name = "adventure-text-serializer-legacy", version.ref = "adventrue" }
adventure-text-serializer-plain = { group = "net.kyori", name = "adventure-text-serializer-plain", version.ref = "adventrue" }
adventure-text-serializer-ansi = { group = "net.kyori", name = "adventure-text-serializer-ansi", version.ref = "adventrue" }